FROM quay.io/maherzubair/sigma-md:beta
RUN git clone https://github.com/Saqlain590/SAQII-MD/root/Saqlain590/SAQII-MD
WORKDIR /root/Saqlain590/SAQII-MD/
RUN npm install npm@latest
RUN npm install
EXPOSE 8000
CMD ["npm", "start"]
 
 
